import Head from "next/head";
import { HomeTemplate } from "@/templates";

export default function Home() {
	return (
		<>
			<Head>
				<title>HVEX - Omni trafo</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<meta
					name="description"
					content="Tenha Informações em tempo real das condições dos ativos e com o monitoramento inteligente"
				/>
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<HomeTemplate />
		</>
	);
}
